In [1]:
import numpy as np
import pandas as pd
from nsepy import get_history
from datetime import date
import lxml
SYMBOL_STOCK = "WIPRO"
SYMBOL_NEWS = "WIPRO"

In [2]:
data = get_history(symbol = SYMBOL_STOCK, start = date(2000,1,1), end = date(2018,3,18))
data.to_csv("../data/"+SYMBOL_STOCK+'_stocks.csv',index = True)
data.sample(5)

,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
Date,,,,,,,,,,,,,,
2005-08-04,WIPRO,EQ,731.90,737.0,739.0,725.0,731.35,731.60,732.74,327394,2.398941e+13,NaN,118825.0,0.3629
2010-12-06,WIPRO,EQ,427.60,430.0,436.6,428.9,430.55,430.65,433.56,1362630,5.907770e+13,NaN,861675.0,0.6324
2005-03-02,WIPRO,EQ,675.65,680.0,683.0,666.0,671.00,671.10,672.04,534558,3.592422e+13,NaN,198391.0,0.3711
2010-09-29,WIPRO,EQ,441.50,441.5,450.2,437.5,441.50,442.35,442.70,1115818,4.939702e+13,NaN,534505.0,0.4790
2004-02-18,WIPRO,EQ,1608.45,1620.0,1626.0,1585.6,1586.00,1590.60,1605.59,290436,4.663207e+13,NaN,29197.0,0.1005